// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Lm6ue8a9jDzawuFBX7YUI_p5RnPFd_g',
    appId: '1:548761890060:web:906fde60894579988a2d29',
    messagingSenderId: '548761890060',
    projectId: 'my-bank-auth-local',
    authDomain: 'my-bank-auth-local.firebaseapp.com',
    storageBucket: 'my-bank-auth-local.appspot.com',
    measurementId: 'G-Z4HBJTMQPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLWmewObE2KUh-dl_F4G1oBS7_EdeFdE',
    appId: '1:548761890060:android:c6151a8ff05da90e8a2d29',
    messagingSenderId: '548761890060',
    projectId: 'my-bank-auth-local',
    storageBucket: 'my-bank-auth-local.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxF5Nw9jb5fdsy_xedQ-4QJNNT9_pA3_Y',
    appId: '1:548761890060:ios:397fb45aadb609e48a2d29',
    messagingSenderId: '548761890060',
    projectId: 'my-bank-auth-local',
    storageBucket: 'my-bank-auth-local.appspot.com',
    iosBundleId: 'com.example.myBankAuthLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxF5Nw9jb5fdsy_xedQ-4QJNNT9_pA3_Y',
    appId: '1:548761890060:ios:ef2e8baea4a1eb638a2d29',
    messagingSenderId: '548761890060',
    projectId: 'my-bank-auth-local',
    storageBucket: 'my-bank-auth-local.appspot.com',
    iosBundleId: 'com.example.myBankAuthLocal.RunnerTests',
  );
}
